### ISSUE TITLE
magic __call

### ISSUE THREAD

**Issue by cradenbyrg** [neosmart/paypalnvp-php#2]
Hi, I'm not sure but I thought the second parameter for __call is an array of the arguments, meaning to say that $fields will be $arguments[0]

Line 86: return $this->GenericNvp($method, $fields);
Line 86: return $this->GenericNvp($method, $fields[0]);

**Comment by cradenbyrg** [comment]
or 

public function __call($method, $arguments) {
    return $this->GenericNvp($method, $arguments[0]);
}

**Comment by mqudsi** [comment]
You're right, of course. Fixed and committed. Thank you.
